# -*- coding: utf-8 -*-
"""capture_list_tumblr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lYbOeArR2pWLdOO5kjPwrG8bbvFdf1He
"""

import re
import pandas as pd
import csv
from bs4 import BeautifulSoup
import requests

url = 'https://getcrazywith.tumblr.com/post/625388133546082304/idclumbthicknessunifcellsizeunifcellshapem'

# Make a GET request to fetch the raw HTML content
html_content = requests.get(url).text

# Parse the html content
soup = BeautifulSoup(html_content)

data = soup.findAll("div", {"class": "T"})


def visible(element):
    if element.parent.name in ['style', 'script', '[document]', 'head', 'title']:
        return False
    elif re.match('<!--.*-->', str(element.encode('utf-8'))):
        return False
    return True


def clean_html(raw_html):
    cleaner = re.compile('<.*?>')
    raw_html = re.sub('<br/>', '\n', raw_html)
    clean_text = re.sub(cleaner, '', raw_html)
    return clean_text


txt = filter(visible, data)

result = list(txt)

str_cleaned = clean_html(str(result[0]))

###############################################
#type(str_cleaned)

###############################################
def Convert(string): 
    text = list(string.split(" ")) 
    return text  

text_convertido = Convert(str_cleaned)

#print(text_convertido) 

############################

with open("test.csv", "w") as f:
    f.write("\n".join(text_convertido))